package com.example.chessrepertoiretrainer.core.ui.theme

import androidx.compose.ui.graphics.Color

// ---------------------------------------------------------------------------
// DARK_WOOD — chess.com-style espresso + warm gold
// ---------------------------------------------------------------------------

val DarkWood_Primary = Color(0xFFC8A45A)
val DarkWood_OnPrimary = Color(0xFF1A0F00)
val DarkWood_PrimaryContainer = Color(0xFF3D2800)
val DarkWood_OnPrimaryContainer = Color(0xFFF0D090)
val DarkWood_Secondary = Color(0xFFA0856B)
val DarkWood_OnSecondary = Color(0xFF1A0A00)
val DarkWood_SecondaryContainer = Color(0xFF2E1F10)
val DarkWood_OnSecondaryContainer = Color(0xFFD9BFA8)
val DarkWood_Tertiary = Color(0xFF6CA06C)
val DarkWood_OnTertiary = Color(0xFF002000)
val DarkWood_TertiaryContainer = Color(0xFF0F2B0F)
val DarkWood_OnTertiaryContainer = Color(0xFFA8D4A8)
val DarkWood_Background = Color(0xFF1E1510)
val DarkWood_OnBackground = Color(0xFFEDE0CC)
val DarkWood_Surface = Color(0xFF27201A)
val DarkWood_OnSurface = Color(0xFFEDE0CC)
val DarkWood_SurfaceVariant = Color(0xFF3A2E24)
val DarkWood_OnSurfaceVariant = Color(0xFFC8B8A4)
val DarkWood_Outline = Color(0xFF7A6650)
val DarkWood_Error = Color(0xFFFFB4AB)
val DarkWood_OnError = Color(0xFF690005)
val DarkWood_ErrorContainer = Color(0xFF93000A)
val DarkWood_OnErrorContainer = Color(0xFFFFDAD6)

val DarkWoodLight_Primary = Color(0xFF6B4C1E)
val DarkWoodLight_OnPrimary = Color(0xFFFFFFFF)
val DarkWoodLight_PrimaryContainer = Color(0xFFF5E0B0)
val DarkWoodLight_OnPrimaryContainer = Color(0xFF2A1600)
val DarkWoodLight_Secondary = Color(0xFF7A5C3A)
val DarkWoodLight_OnSecondary = Color(0xFFFFFFFF)
val DarkWoodLight_SecondaryContainer = Color(0xFFF0D8B8)
val DarkWoodLight_OnSecondaryContainer = Color(0xFF2A1400)
val DarkWoodLight_Tertiary = Color(0xFF3A7A3A)
val DarkWoodLight_OnTertiary = Color(0xFFFFFFFF)
val DarkWoodLight_TertiaryContainer = Color(0xFFC0E8C0)
val DarkWoodLight_OnTertiaryContainer = Color(0xFF002000)
val DarkWoodLight_Background = Color(0xFFFDF6EC)
val DarkWoodLight_OnBackground = Color(0xFF1E1510)
val DarkWoodLight_Surface = Color(0xFFFDF6EC)
val DarkWoodLight_OnSurface = Color(0xFF1E1510)
val DarkWoodLight_SurfaceVariant = Color(0xFFEDE0CC)
val DarkWoodLight_OnSurfaceVariant = Color(0xFF4A3C2C)
val DarkWoodLight_Outline = Color(0xFF8A7058)
val DarkWoodLight_Error = Color(0xFFBA1A1A)
val DarkWoodLight_OnError = Color(0xFFFFFFFF)
val DarkWoodLight_ErrorContainer = Color(0xFFFFDAD6)
val DarkWoodLight_OnErrorContainer = Color(0xFF410002)

// ---------------------------------------------------------------------------
// LICHESS — Lichess charcoal + signature green
// ---------------------------------------------------------------------------

val Lichess_Primary = Color(0xFF629924)
val Lichess_OnPrimary = Color(0xFFFFFFFF)
val Lichess_PrimaryContainer = Color(0xFF1C3A00)
val Lichess_OnPrimaryContainer = Color(0xFFA8D870)
val Lichess_Secondary = Color(0xFF5A8FCC)
val Lichess_OnSecondary = Color(0xFFFFFFFF)
val Lichess_SecondaryContainer = Color(0xFF1A2E44)
val Lichess_OnSecondaryContainer = Color(0xFF9DCAFF)
val Lichess_Tertiary = Color(0xFFC89B20)
val Lichess_OnTertiary = Color(0xFF1A1000)
val Lichess_TertiaryContainer = Color(0xFF302000)
val Lichess_OnTertiaryContainer = Color(0xFFF0CC70)
val Lichess_Background = Color(0xFF161512)
val Lichess_OnBackground = Color(0xFFBABABA)
val Lichess_Surface = Color(0xFF202020)
val Lichess_OnSurface = Color(0xFFBABABA)
val Lichess_SurfaceVariant = Color(0xFF2A2A2A)
val Lichess_OnSurfaceVariant = Color(0xFF909090)
val Lichess_Outline = Color(0xFF505050)
val Lichess_Error = Color(0xFFFFB4AB)
val Lichess_OnError = Color(0xFF690005)
val Lichess_ErrorContainer = Color(0xFF93000A)
val Lichess_OnErrorContainer = Color(0xFFFFDAD6)

val LichessLight_Primary = Color(0xFF4A7A10)
val LichessLight_OnPrimary = Color(0xFFFFFFFF)
val LichessLight_PrimaryContainer = Color(0xFFD0F0A0)
val LichessLight_OnPrimaryContainer = Color(0xFF102000)
val LichessLight_Secondary = Color(0xFF2A5F9F)
val LichessLight_OnSecondary = Color(0xFFFFFFFF)
val LichessLight_SecondaryContainer = Color(0xFFBBDEFF)
val LichessLight_OnSecondaryContainer = Color(0xFF001A34)
val LichessLight_Tertiary = Color(0xFF8A6A00)
val LichessLight_OnTertiary = Color(0xFFFFFFFF)
val LichessLight_TertiaryContainer = Color(0xFFF8DC70)
val LichessLight_OnTertiaryContainer = Color(0xFF241A00)
val LichessLight_Background = Color(0xFFF5F5F0)
val LichessLight_OnBackground = Color(0xFF1A1A1A)
val LichessLight_Surface = Color(0xFFFFFFFF)
val LichessLight_OnSurface = Color(0xFF1A1A1A)
val LichessLight_SurfaceVariant = Color(0xFFE8EAE0)
val LichessLight_OnSurfaceVariant = Color(0xFF3C4030)
val LichessLight_Outline = Color(0xFF8A8E80)
val LichessLight_Error = Color(0xFFBA1A1A)
val LichessLight_OnError = Color(0xFFFFFFFF)
val LichessLight_ErrorContainer = Color(0xFFFFDAD6)
val LichessLight_OnErrorContainer = Color(0xFF410002)

// ---------------------------------------------------------------------------
// WARM_LIGHT — aged parchment + library red
// ---------------------------------------------------------------------------

val WarmLight_Primary = Color(0xFF7B2C2C)
val WarmLight_OnPrimary = Color(0xFFFFFFFF)
val WarmLight_PrimaryContainer = Color(0xFFF2CCCC)
val WarmLight_OnPrimaryContainer = Color(0xFF350A0A)
val WarmLight_Secondary = Color(0xFF5C4033)
val WarmLight_OnSecondary = Color(0xFFFFFFFF)
val WarmLight_SecondaryContainer = Color(0xFFEEDCCC)
val WarmLight_OnSecondaryContainer = Color(0xFF281408)
val WarmLight_Tertiary = Color(0xFF2B5B34)
val WarmLight_OnTertiary = Color(0xFFFFFFFF)
val WarmLight_TertiaryContainer = Color(0xFFC0E4C8)
val WarmLight_OnTertiaryContainer = Color(0xFF031810)
val WarmLight_Background = Color(0xFFF5EDD8)
val WarmLight_OnBackground = Color(0xFF1C1208)
val WarmLight_Surface = Color(0xFFFAF3E0)
val WarmLight_OnSurface = Color(0xFF1C1208)
val WarmLight_SurfaceVariant = Color(0xFFEDE0C4)
val WarmLight_OnSurfaceVariant = Color(0xFF4A3828)
val WarmLight_Outline = Color(0xFF9A7A60)
val WarmLight_Error = Color(0xFFBA1A1A)
val WarmLight_OnError = Color(0xFFFFFFFF)
val WarmLight_ErrorContainer = Color(0xFFFFDAD6)
val WarmLight_OnErrorContainer = Color(0xFF410002)

val WarmLightDark_Primary = Color(0xFFE89090)
val WarmLightDark_OnPrimary = Color(0xFF350A0A)
val WarmLightDark_PrimaryContainer = Color(0xFF5A1818)
val WarmLightDark_OnPrimaryContainer = Color(0xFFFFD0D0)
val WarmLightDark_Secondary = Color(0xFFC8A890)
val WarmLightDark_OnSecondary = Color(0xFF281408)
val WarmLightDark_SecondaryContainer = Color(0xFF3C2418)
val WarmLightDark_OnSecondaryContainer = Color(0xFFF0D8C0)
val WarmLightDark_Tertiary = Color(0xFF80C890)
val WarmLightDark_OnTertiary = Color(0xFF031810)
val WarmLightDark_TertiaryContainer = Color(0xFF143820)
val WarmLightDark_OnTertiaryContainer = Color(0xFFB0E8C0)
val WarmLightDark_Background = Color(0xFF1C1510)
val WarmLightDark_OnBackground = Color(0xFFEDE0C4)
val WarmLightDark_Surface = Color(0xFF241C14)
val WarmLightDark_OnSurface = Color(0xFFEDE0C4)
val WarmLightDark_SurfaceVariant = Color(0xFF30241A)
val WarmLightDark_OnSurfaceVariant = Color(0xFFC0A888)
val WarmLightDark_Outline = Color(0xFF786050)
val WarmLightDark_Error = Color(0xFFFFB4AB)
val WarmLightDark_OnError = Color(0xFF690005)
val WarmLightDark_ErrorContainer = Color(0xFF93000A)
val WarmLightDark_OnErrorContainer = Color(0xFFFFDAD6)
